version: '3'

services:
  postgres:
    image: "postgres:12"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${LOCAL_HOST}:9092"
