name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Set Up Containers
      run: |
        docker-compose -f ./.github/workflows/docker/docker-compose.yml up -d
        docker ps -a

    - name: Go Get
      run: go get -u -v all

    - name: Build & Test
      run: |
        make
        telnet localhost 9092
        telnet 127.0.0.1 9092
        telnet kafka 9092
        telnet kafka 29092
        telnet localhost 5432

    - name: Integration Test
      run: make int
